### ISSUE TITLE
[WinError 5] Access is denied: 'Stability'

### ISSUE THREAD

**Issue by t0mski3** [besarismaili/Stable-Diffusion-for-NUKE#2]
Dear community. I installed everything as explained.. however I get the following error-message when trying to generate something: 

[WinError 5] Access is denied: 'Stability'

Is this some kind of rights-management issue? How could I solve this please ? 

Many thanks in advance and awesome work !!!

**Comment by Joeb0611** [comment]
I'm having the same issue

`Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Program Files\Nuke14.0v4\python39.zip\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Nuke14.0v4\python39.zip\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'Stability'`

**Comment by Joeb0611** [comment]
I got it working. You must save the nuke script first. The code is using the script path to create folders.

**Comment by besarismaili** [comment]
> 

Please double-check if your API key is correct and make sure you have enough credits.

> Dear community. I installed everything as explained.. however I get the following error-message when trying to generate something:
> 
> [WinError 5] Access is denied: 'Stability'
> 
> Is this some kind of rights-management issue? How could I solve this please ?
> 
> Many thanks in advance and awesome work !!!

**Comment by t0mski3** [comment]
thank you - saving the script already solved it.. apologies to bother <3 great implementation !! Love it Besar
